### ISSUE TITLE
Order by length of tag name

### ISSUE THREAD

**Issue by joshkersey** [chhantyal/taggit-selectize#11]
We have a taggit database of several thousand tags. Some are single words while others are multiple words in a single tag. One of the issues we found in working with Taggit is the ordering of the results would sometimes bury the single word tags below the multiple word tags and they wouldn't appear in the results list.

I solved this by customizing the `get_tags_recommendation()` view for this project. I wanted to share it here in case you find it something worth considering for the project codebase. Perhaps pair it with a setting variable for SORT_TYPE, etc. Happy to put together a pull request if you think it's valuable.

Here's the customized view that I created. Essentially it's the same view just adding the `extra` and `order_by` methods:

```
def get_tags_recommendation(request):
    query = request.GET.get('query')
    limit = settings.TAGGIT_SELECTIZE['RECOMMENDATION_LIMIT']
    if query:
        tags = Tag.objects.filter(name__icontains=query).extra(select={'length':'Length(name)'}).order_by('length').values('name')[:limit]
    else:
        tags = Tag.objects.all().extra(select={'length':'Length(name)'}).order_by('length').values()[:limit]

    data = json.dumps({
        'tags': list(tags)
    })

    return HttpResponse(data, content_type='application/json')
```

**Comment by nshafer** [comment]
Hi Josh,

In looking into this I am a little confused. From what I can tell, Selectize.js does its own sorting of the result set using Sifter.js, and based on scoring a match. Also, from what I can tell, Selectize is [designed to do the sorting on the client side](https://github.com/selectize/selectize.js/issues/640#issuecomment-71788203) and not the server side. Just in some simple tests the cost of adding the sorting on Postgres went from .5 to 33.5, so a massive increase in the work that the database has to do. I don't have a very large dataset to test with, but after looking at how things work and in my testing I don't see a difference between default behavior and your modified function. Have you seen a difference?

**Comment by joshkersey** [comment]
In this particular use case it's a Django admin input for tagging. The admin users were complaining of the single word results not appearing. 

The difference we've seen is that the single word tags are now appearing at the top of the result list rather than not appearing on the result list at all even with `RECOMMENDATION_LIMIT: 30`. On occasion the results are not in precise length order but it's made my client happy.

**Comment by nshafer** [comment]
Hmm, there must be something in either Selectize.js or Sifter.js that is honoring the original sorting in some way or another. For now, we'll just leave it as is. There is nothing stopping you or someone else using this module from making their own view that returns the data any ways they want, but in the interest of performance for the common case, I'll leave the view as-is. Thanks for the info!
