### ISSUE TITLE
with DRF

### ISSUE THREAD

**Issue by pyprism** [chhantyal/taggit-selectize#12]
Any idea how to use it with django rest framework ?

**Comment by chhantyal** [comment]
Hi @pyprism 

That is out of scope for this project. If you want to use DRF backend you can, even currently it just returns json response when selectize sends ajax response https://github.com/chhantyal/taggit-selectize/blob/master/taggit_selectize/views.py

So if you have different view, you could just override 

```
    url(r'^taggit/', include('taggit_selectize.urls')),
```

However, some of the settings won't work as expected. 

For this autocomplete use, DRF is overkill.
