### ISSUE TITLE
ModuleNotFoundError: No module named 'taggit-selectize'

### ISSUE THREAD

**Issue by enzlo** [chhantyal/taggit-selectize#26]
Installed just the way as listed in the README.md and ran into this error

`ModuleNotFoundError: No module named 'taggit-selectize'`

I've uninstalled the package several times and installed it via pip and requirements both give me the same issue. Also, tried this similar issue answer but no luck https://github.com/esoergel/peacecorps/issues/37, Any ideas?

**Comment by chhantyal** [comment]
I bet you need to use underscore `taggit_selectize` in INSTALLED_APPS section.

**Comment by enzlo** [comment]
My god you were right. I apologize for even making this an issue...
