### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by MrAlexWinkler** [chhantyal/taggit-selectize#27]
six is not available in django.utils in Django 3

"six" was depreciated from django.utils
https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

Found a possible answer here
https://stackoverflow.com/questions/59193514/importerror-cannot-import-name-six-from-django-utils

This is a package that replaces it
https://pypi.org/project/six/

Wherever "six" was you can replace it with PY3
https://six.readthedocs.io/

Make sure to replace
from django.utils import six
with
from six import *

New issue appeared 

...\venv\lib\site-packages\taggit_selectize\widgets.py in render, line 22
'bool' object has no attribute 'string_types'

**Comment by cruzlutor** [comment]
Same issue here

**Comment by chhantyal** [comment]
Fixed #28
