### ISSUE TITLE
RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().

### ISSUE THREAD

**Issue by charleszlu** [chhantyal/taggit-selectize#37]
`force_text()` is deprecated and is being removed in Django 4.0 (to be released in December), the replacement is `force_str()`.

Currently on Django 3.2 it gives a RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  tagstring = force_text(tagstring)

https://github.com/chhantyal/taggit-selectize/blob/faa4cd8d98cecc0562ff265a7cf800cc4a8f4885/taggit_selectize/utils.py#L23

**Comment by chhantyal** [comment]
Merged the PR and released: https://pypi.org/project/taggit-selectize/2.11.0/
