### ISSUE TITLE
RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path()

### ISSUE THREAD

**Issue by charleszlu** [chhantyal/taggit-selectize#38]
The following should be replaced with `django.urls.re_path` to be compatible with Django 4.0:

https://github.com/chhantyal/taggit-selectize/blob/faa4cd8d98cecc0562ff265a7cf800cc4a8f4885/taggit_selectize/urls.py#L6

**Comment by charleszlu** [comment]
This PR would mean the minimum django version required becomes 2.2 (`force_str` is introduced in 2.2), if that is OK.

**Comment by chhantyal** [comment]
Merged the PR and released: https://pypi.org/project/taggit-selectize/2.11.0/
